//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCorp_Mail_Client.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10, 14, 29")]
        public global::System.Drawing.Color bgd_00dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_00dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22, 26, 41")]
        public global::System.Drawing.Color bgd_01dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_01dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("27, 31, 45")]
        public global::System.Drawing.Color bgd_02dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_02dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29, 33, 47")]
        public global::System.Drawing.Color bgd_03dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_03dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32, 36, 49")]
        public global::System.Drawing.Color bgd_04dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_04dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("37, 40, 54")]
        public global::System.Drawing.Color bgd_06dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_06dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 43, 56")]
        public global::System.Drawing.Color bgd_08dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_08dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("45, 48, 61")]
        public global::System.Drawing.Color bgd_12dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_12dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("47, 50, 63")]
        public global::System.Drawing.Color bgd_16dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_16dp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("49, 53, 65")]
        public global::System.Drawing.Color bgd_24dp {
            get {
                return ((global::System.Drawing.Color)(this["bgd_24dp"]));
            }
        }
    }
}
